server:
  port: 9888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///czb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:
    password:
#    username: root
#    password: root
redis:
  host: 127.0.0.1
#jwt:
#  config:
#    key: www.ccstay.com.by.cc
#    ttl: 3600000
aliyun:
  sms:
    accessKeyId:
    accessKeySecret:
    template_code: SMS_184205569
    sign_name: CC
